package iwp.crawler.iwpcrawler.utils;

import java.util.Arrays;
import java.util.List;

public class AmazonSelectors {

    public static final String AMAZON_URL = "https://www.amazon.com/";
    public static final String AMAZON_CATEGORY_URL = AMAZON_URL+"gp/site-directory";
    public static final String AMAZON_QUERY_SEARCH = AMAZON_URL+"s?k=";
    public static final String CATEGORIES_FSD_COLUMN_SELECTOR = "div[class=\"a-column a-span3 fsdColumn fsdColumn_3\"]";
    public static final String CATEGORY_FSD_BOX_SELECTOR = "div[class=\"fsdDeptBox\"]";
    public static final String CATEGORY_ROOT_TITLE_SELECTOR = "h2[class=\"fsdDeptTitle\"]";
    public static final String SUB_CATEGORY_SELECTOR = "a[class=\"a-link-normal fsdLink fsdDeptLink\"]";
    public static final String DEPARTEMENT_SELECTOR = "li[class=\"a-spacing-micro s-navigation-indent-1\"]";
    public static final String DEPARTEMENT_CATEGORY_SELECTOR = "span[class=\"a-size-base a-color-base\"]";
    public static final String DEPARTEMENT_HREF_SELECTOR = "a[data-routing=\"off\"]";

    public static final List<String> AMAZON_EXCLUDED_CATEGORIES = Arrays.asList(
            "Prime Video", "Amazon Music", "Echo & Alexa", "Appstore for Android",
            "Alexa Smart Home", "AmazonFresh", "Food & Grocery", "Whole Foods Market", "Make Money with Amazon",
            "Home Services", "Credit & Payment Products", "Amazon Business", "Amazon Launchpad", "Amazon Exclusives",
            "Subscribe with Amazon", "Amazon Live", "Treasure Truck", "International Shopping", "Amazon Photos and Prints",
            "Small & Medium Businesses", "Fire TV", "Fire Tablets", "Clothing, Shoes, Jewelry & Watches"
    );

    public static final String EXCLUDE_AMAZON_PATTERN =
            ".*(Alexa|alexa|Streaming|Amazon|amazon|Prime|prime|Coupon|coupon|Free|Business|Echo|" +
                    ".com|Download|download|Membership|membership|Shopping|shopping|Sales|Sell|Deals|Shop|Brand|Rental|Unlimited|Gift|Trade|Discover|Made in).*|App";

    private AmazonSelectors(){}



    public static List<String> departements = Arrays.asList(

            "Women's Accessories",
            "Women's Jewelry",
            "Women's Hats & Caps",
            "Women's Necklaces",
            "Women's Lingerie Accessories",
            "Women's Wrist Watches",
            "PC Accessories",
            "Wii Accessories",
            "PlayStation 3 Accessories",
            "Xbox Accessories",
            "PlayStation 4 Accessories",
            "Nintendo 3DS & 2DS Accessories",
            "PlayStation Accessories",
            "Xbox 360 Accessories",
            "NES Accessories",
            "Xbox One Accessories",
            "Men's Accessories",
            "Iphone",
            "Girls' Accessories",
            "Boys' Accessories",
            "Girls' Costume Accessories",
            "Boys' Costume Accessories",
            "Men's Costume Accessories",
            "Women's Costume Accessories",
            "Men's Costume Masks",
            "Cell Phone Car Kits",
            "Kids' Costume Accessories",
            "Gags & Practical Joke Toys",
            "Wearable Technology",
            "Computer Gaming Chairs",
            "Air Conditioner Accessories",
            "Novelty Clothing",
            "Automotive",
            "Accessories",
            "Heaters & Heater Accessories",
            "Cloud Computing",
            "Computers & Technology",
            "Computer Networks, Protocols & APIs",
            "Computer Graphics & Design",
            "Graphics & Multimedia Programming",
            "Computer Networking",
            "Computer Graphic Design",
            "Home Publishing",
            "Home & Hobby Downloads",
            "Book Readers & Players",
            "Document Viewers",
            "Almanacs & Yearbooks",
            "Movie & Video Reference",
            "Video Reference",
            "Architecture Reference",
            "Yearbooks & Annuals",
            "Maps",
            "Vocabulary, Slang & Word Lists",
            "30-Minute Computers & Technology Short Reads",
            "30-Minute Education & Reference Short Reads",
            "Information Technology",
            "Children's Classics",
            "Children's Books",
            "Early Learning Beginner Readers",
            "Children's Humor",
            "Children's Literature",
            "Children's Colors Books",
            "Children's Rabbit Books",
            "Children's Bear Books",
            "Children's Beginner Readers",
            "Children's Poetry",
            "Children's Classic Literature",
            "Baby & Toddler Bedtime & Dreaming Books",
            "Children's eBooks",
            "Baby & Toddler Beginner Readers Books",
            "Children's Animal Stories",
            "Children's Humorous Literature",
            "Women's Interest Magazines",
            "Entertainment & Pop Culture Magazines",
            "Home Decorating Magazines",
            "Science, History & Nature Magazines",
            "Travel, City & Regional Magazines",
            "Recipes & Techniques Magazines",
            "Health Magazines",
            "Cooking, Food & Wine Magazines",
            "History Trade Journals",
            "Women's Fashion Magazines",
            "Kindle Newsstand",
            "Lifestyle & Culture eMagazines",
            "Security & Encryption",
            "Network Security",
            "Collectible Magazines & Newspapers",
            "Journalism Writing Reference",
            "Essays",
            "Hiking & Camping Instructional Guides",
            "Hiking & Camping Excursion Guides",
            "Cookbooks, Food & Wine",
            "Running & Jogging",
            "Low Fat Cooking",
            "Antique & Collectible Magazines & Newspapers",
            "Computer Hacking",
            "Computer Network Security",
            "Schools & Teaching",
            "General Surgery",
            "Medical & Surgical Nursing",
            "Pediatrics",
            "Pediatric Perinatology & Neonatology",
            "Astronomy",
            "Mathematics",
            "Academic Development Counseling",
            "Critical Care",
            "Nursing Fundamentals & Skills",
            "Perinatology & Neonatology",
            "Kindle eBooks",
            "Biology",
            "Nonfiction",
            "Blu-ray",
            "Movies",
            "Blu-ray 3D",
            "Music Videos & Concerts",
            "Action & Adventure",
            "Drama",
            "Mystery & Thrillers",
            "Science Fiction",
            "Horror",
            "TV",
            "Blu-Ray Disc Players",
            "Streaming Media Players",
            "Home Theater Systems",
            "Internal Blu-ray Drives",
            "Literature & Fiction",
            "Short Stories",
            "Science Fiction & Fantasy",
            "Short Stories Anthologies",
            "Fantasy Anthologies",
            "Science Fiction Short Stories",
            "Magical Realism",
            "Crime Thrillers",
            "Mystery, Thriller & Suspense",
            "Mystery Anthologies",
            "Single Authors Short Stories",
            "Fantasy TV, Movie & Game Tie-In",
            "Contemporary Short Stories",
            "U.S. Short Stories",
            "Fantasy",
            "Fantasy Anthologies & Short Stories",
            "Science Fiction TV, Movie & Game Tie-In",
            "Two-Hour Literature & Fiction Short Reads",
            "Video Projectors",
            "Women's Panties",
            "Boys' Tops & Tees",
            "Kids & Family",
            "Blank CD-R Discs",
            "Disc Jewel Cases",
            "Pop",
            "Broadway & Vocalists",
            "Vocal Pop",
            "Children's Action & Adventure Books",
            "Children's Fantasy & Magic Books",
            "Children's Folk Tales & Myths",
            "Foreign Dictionaries & Thesauruses",
            "Words, Language & Grammar",
            "Travel Language Phrasebooks",
            "Reference",
            "Christian Music",
            "New Age",
            "MP3 & MP4 Players",
            "MP3 & MP4 Player Accessories",
            "MP3 Player & Cell Phone Audio Docks",
            "Car Audio Receivers",
            "Car Stereo Digital Media Receivers",
            "Digital Voice Recorders",
            "Music",
            "MIDI & Mixers",
            "Web Development & Design",
            "Music History & Criticism",
            "Music Business",
            "Communication & Media Studies",
            "Music Recording & Sound",
            "Computer Software",
            "Jewelry Boxes",
            "Jewelry Music Boxes",
            "Music eBooks",
            "Digital Media",
            "Music Recording Equipment",
            "Audio Headphones",
            "Over-Ear Headphones",
            "On-Ear Headphones",
            "Earbud & In-Ear Headphones",
            "Headphone Earpads",
            "Electronic Equipment Warranties",
            "Headphone Adapters",
            "Computer Headsets",
            "Computer Accessories & Peripherals",
            "DJ Headphones",
            "Wireless Headset Microphones & Systems",
            "Cell Phone Accessories",
            "PlayStation 4 Games",
            "PlayStation 3 Games",
            "Xbox 360 Games",
            "Xbox One Games",
            "Wii Games",
            "Nintendo DS Games",
            "3DO Games",
            "Atari 2600 Games",
            "Atari 5200 Games",
            "Atari 7800 Games",
            "Video Game Art",
            "Computer & Video Game Strategy Guides",
            "Science Fiction Adventures",
            "Video & Computer Games",
            "Video & Electronic Games",
            "Science Fiction Adventure",
            "Video Games",
            "Desktop Computers",
            "Tower Computers",
            "Computer Components",
            "PC Games & Accessories",
            "Kids & Family Games & Consoles",
            "PC Gaming Keyboards",
            "PC Digital Games & DLC",
            "PC-compatible Games",
            "PC Game Controllers",
            "Children's Software Games",
            "Children's Software Games Downloads",
            "Games",
            "Children's Software",
            "Home Office Desks",
            "Xbox One Digital Games",
            "Xbox 360 Digital Games",
            "Digital Game Downloads",
            "Xbox One Kids & Family Games",
            "Nintendo Switch Digital Games",
            "Nintendo Switch Games",
            "Xbox 360 Kids & Family Games",
            "Wii U Games",
            "Digital Audio, Video & Photography",
            "Computer & Video Game Design",
            "Children's Video & Electronic Games Books",
            "Children's Computers & Technology Books",
            "Computers & Technology Education",
            "Pedagogy",
            "Children's Computer & Technology Books",
            "Children's Computer Games",
            "Children's Video & Electronic Game Books",
            "Entertainment Collectibles",
            "Entertainment Collectible Compact Discs & Inserts",
            "Entertainment Collectible Movies & Music",
            "Humor & Entertainment",
            "Collections, Catalogs & Exhibitions",
            "Graphic Novels",
            "Performing Arts",
            "Comic Strips",
            "Actor & Entertainer Biographies",
            "Comics & Graphic Novels",
            "Satire",
            "Graphic Novel Anthologies",
            "Cartoons",
            "Comics, Manga & Graphic Novels",
            "Two-Hour Humor & Entertainment Short Reads",
            "Humor",
            "Art Book Graphic Novels",
            "Two-Hour Comic & Graphic Novel Short Reads",
            "Media Tie-In & Adaptation Graphic Novels",
            "Fantasy Graphic Novels",
            "Collectible Figurines",
            "Collectible Trading Card Decks & Sets",
            "DVD",
            "LED & LCD TVs",
            "Televisions",
            "Televisions & Video Products",
            "Movies & TV",
            "Audio/Video Receivers & Amplifiers",
            "Surround Sound Systems",
            "Home Audio & Theater Products",
            "Stereo Shelf Systems",
            "Audio Component Amplifiers",
            "Audio Component Receivers",
            "Floorstanding Speakers",
            "Home Audio Crossovers",
            "Audio Cables",
            "Radio",
            "General Broadcasting",
            "Humorous American Literature",
            "Jokes & Riddles",
            "Stage & Studio Speaker Cables",
            "Hidden Cameras",
            "Pet Cameras & Monitors",
            "Scrapbooking",
            "Graphics",
            "Computer Printer Parts & Accessories",
            "Photo Quality Paper",
            "Inkjet Printer Paper",
            "Kids' Cameras & Camcorders",
            "Scrapbooking Photo Mounting Corners",
            "Powersports Photography Equipment",
            "Security & Surveillance Equipment",
            "Bluetooth Car Kits",
            "Wireless & Streaming Audio Systems",
            "Audio & Video Accessories",
            "Portable Bluetooth Speakers",
            "Wireless Audio Receivers & Adapters",
            "Single Ear Bluetooth Cell Phone Headsets",
            "Cell Phone Car Speakerphones",
            "Bluetooth Computer Network Adapters",
            "USB Computer Network Adapters",
            "Novelty",
            "Utilities",
            "Car Electronics",
            "MP3 Player FM Transmitters",
            "Aviation Electronics",
            "Car Electronics Accessories",
            "Aviation Handheld Two-Way Radios",
            "Cell Phone Car Cradles & Mounts",
            "Cell Phone Car Chargers",
            "Cell Phone Car Accessories",
            "Electronics Kits",
            "Electronic Learning & Education Toys",
            "Kids' Handheld Games",
            "Kids' Electronics",
            "Hobby RC Quadcopters & Multirotors",
            "Budgeting & Money Management",
            "Musical Instruments",
            "Children's Musical Instruments",
            "Kids' Drum & Percussion Instruments",
            "Kids' Musical Instruments",
            "Ukuleles",
            "Thumb Pianos",
            "Fitness Trackers",
            "Fitness Technology",
            "Running Equipment",
            "Wristbands",
            "Electronics & Gadgets",
            "Smartwatches",
            "Smart Clips, Arm & Wristbands",
            "Electronic Sensors",
            "Fashion Design",
            "Computer Hardware & DIY",
            "Single Board Computers",
            "Microelectronics",
            "Electronics",
            "Electrical & Electronic Circuits",
            "Circuit Design",
            "Activity, Health & Wellness Monitors",
            "Commercial Fashion",
            "Computer Hardware",
            "Electrical & Electronics",
            "Circuit Engineering",
            "Microelectronics Engineering",
            "Christian Living",
            "Love & Romance",
            "Real Estate",
            "Interpersonal Relations",
            "Motivational Self-Help",
            "Buying & Selling Homes",
            "Christian Literature & Fiction",
            "Investing",
            "Stock Market Investing",
            "Personal Transformation Self-Help",
            "Reality TV",
            "Documentary",
            "How-to & Home Improvement",
            "Entrepreneurship",
            "Investing Basics",
            "Home Design Remodeling & Renovation",
            "Small Business & Entrepreneurship",
            "90-Minute Business & Money Short Reads",
            "Jewelry Making Findings",
            "Computers & Tablets",
            "Computer Speakers",
            "Computer Keyboards",
            "USB Cables",
            "Office Carts & Stands",
            "Laptop Computer Stands",
            "Computer Tablet Books",
            "Internet & Telecommunications",
            "Mac Hardware",
            "Internet Culture",
            "Two-Hour Computers & Technology Short Reads",
            "Tablet Guides",
            "Mac Computer Hardware",
            "Tech Culture & Computer Literacy",
            "Computer Monitors",
            "Computer Monitor Accessories",
            "Environmental Engineering",
            "Computer Networks",
            "Networking & Cloud Computing",
            "Communication Skills",
            "Sales & Selling",
            "Business & Money",
            "Business & Investing Skills",
            "Marketing for Small Businesses",
            "Small Business Sales & Selling",
            "Business Office Skills",
            "Business Marketing & Sales",
            "Business & Money Skills",
            "Socket Sets",
            "Individual Drive Sockets",
            "Travel",
            "Road Travel Reference",
            "US Travel Guides",
            "Children's Horse Books",
            "Pacific West United States Travel Books",
            "Driver's Education",
            "General Oregon Travel Guides",
            "Automotive Replacement Universal Joints & Parts",
            "Automotive Replacement Drive Shaft Assemblies",
            "Computer Motherboards",
            "Computer & Mobile Device Repair Kits",
            "Computer Cases",
            "Computer Power Supplies",
            "Internal Fans & Cooling Components",
            "Computer Case Fans",
            "Education for Kids",
            "Automotive Replacement Ignition Parts",
            "PC Hardware",
            "Computers & Technology Teaching & Reference",
            "Two-Hour Education & Reference Short Reads",
            "90-Minute Education & Reference Short Reads",
            "Networking & Servers",
            "Programming & Web Development",
            "CD Burning & Labeling",
            "Software Downloads",
            "Audio Editing & Effects",
            "Music Downloads",
            "CD Burning & Labeling Downloads",
            "Audio Editing & Effects Downloads",
            "Software Development",
            "Computer Programming",
            "Programming Languages",
            "Software Project Management",
            "IT Project Management",
            "Inkjet Computer Printers",
            "Computer Printers",
            "Laser Computer Printers",
            "Printers & Accessories",
            "Computer Printer Ink & Toner",
            "Computer Cables & Interconnects",
            "Office & School Supplies",
            "Desk Supplies Holders & Dispensers",
            "Office Storage Supplies",
            "Filing Products",
            "Drawer Organizers",
            "Office Furniture & Lighting",
            "File Folder Racks & File Folder Holders",
            "Desktop Shelves & Office Shelves",
            "Monitor Arms & Monitor Stands",
            "Office Racks & Displays",
            "Comedy",
            "Prime Video",
            "Sports",
            "Business & Office Management",
            "Business & Office",
            "Word Processing",
            "Internet Utilities",
            "Document Editing",
            "Power Strips",
            "Cable Straps",
            "Hammock Stands",
            "Geographic Globes",
            "Stationery Notepads",
            "Cell Phone Stands",
            "Sofas & Couches",
            "Living Room Furniture",
            "Television Stands",
            "Bedroom Furniture",
            "Sofa Tables",
            "Coffee Tables",
            "Media Storage",
            "Ottomans & Storage Ottomans",
            "Kitchen & Dining Room Furniture",
            "Living Room Furniture Sets",
            "Bar Coasters",
            "Kids' Furniture & Décor",
            "Home Furniture",
            "Antique & Collectible Furniture",
            "Furniture Design",
            "Woodworking Projects",
            "Furniture & Carpentry Crafts",
            "Woodworking",
            "Crafts & Hobbies",
            "Patio Bistro Sets",
            "Patio Conversation Sets",
            "Patio Sofas",
            "Office Shelving & Office Storage",
            "Furniture How-to & Home Improvement",
            "Camping Chairs",
            "Outdoor String Lights",
            "Wall Stickers & Murals",
            "Jewelry Armoires",
            "Kitchen Cookware Sets",
            "Food Storage & Organization Sets",
            "Fruit & Vegetable Corers",
            "Mixing Bowls",
            "Sandwich Makers & Panini Presses",
            "Kitchen Utensils & Gadgets",
            "Literary Fiction",
            "Contemporary Literature & Fiction",
            "Psychological Fiction",
            "Japanese Literature",
            "Literary Criticism",
            "Asian Literary History & Criticism",
            "Special Diet Cooking",
            "U.S. Regional Cooking, Food & Wine",
            "Toy Kitchen Sets",
            "Early Development Activity Centers",
            "Beds",
            "Beds, Frames & Bases",
            "Mattresses",
            "Mattresses & Box Springs",
            "Bed Frames",
            "Bedroom Sets",
            "Bedding Comforters",
            "Bedding",
            "Air Mattresses",
            "Camping Air Mattresses",
            "Planters",
            "Raised Garden Kits",
            "Vegetable Plants & Seeds",
            "Outdoor Decorative Stones",
            "Outdoor Statues",
            "Plant Germination Kits",
            "Gardening Pots, Planters & Accessories",
            "Greenhouses",
            "Gardening Gloves",
            "Garden Tool Sets",
            "Power Tools & Hand Tools",
            "Landscape Path Lights",
            "Outdoor Figurine Lights",
            "Garden Design",
            "Container Gardening",
            "Handmade Garden Stakes",
            "Mattress & Box Spring Sets",
            "Mattresses Toppers",
            "Mattress Pads",
            "Electric Mattress Pads",
            "Mattress Pads & Protectors",
            "Mattress Protectors",
            "Convoluted Mattress Foam",
            "Pendant Light Fixtures",
            "Chandeliers",
            "Close To Ceiling Light Fixtures",
            "Lighting & Ceiling Fans",
            "Vanity Lighting Fixtures",
            "Floor Lamps",
            "Under-Counter Light Fixtures",
            "Complete Track Lighting Kits",
            "Lighting Soft Boxes",
            "Photographic Lighting Umbrellas",
            "Continuous Output Lighting",
            "Indoor String Lights",
            "Rope Lights",
            "Home Decorative Accessories",
            "Home Storage & Organization",
            "Closet Storage & Organization Systems",
            "Kids' Furniture",
            "Standing Shelf Units",
            "Under-Bed Storage",
            "Bookcases",
            "Clothing & Closet Storage",
            "Storage Drawer Units",
            "Shoe Organizers",
            "Garage Storage & Organization Products",
            "Tool Utility Shelves",
            "Utility Racks",
            "Toy Chests & Storage",
            "Craft & Sewing Supplies Storage",
            "Arts & Crafts Storage Boxes & Organizers",
            "Arts, Crafts & Sewing Storage",
            "Art Storage Cabinets",
            "Kitchen Storage & Organization",
            "Storage Drawer Carts",
            "Desk Accessories & Workspace Organizers",
            "Modular Storage Systems",
            "Toy Chests & Organizers",
            "Nursery Hanging Organizers",
            "Cosmetic Display Cases",
            "Fine Art",
            "Fine Art Oil Paintings",
            "Greeting Cards",
            "Arts & Photography",
            "Arts & Photography Criticism",
            "Art History",
            "Graphic Design",
            "Graphic Design Clip Art",
            "Decorative Arts",
            "Individual Artists' Books",
            "Pop Culture Art",
            "Art Encyclopedias",
            "Art",
            "Antique & Collectible Art",
            "Fine Arts",
            "Sports Collectibles",
            "Collectible Coins",
            "Collectible Coin Sets",
            "Grown-Up Action & Toy Figures",
            "Antique & Collectible Reference",
            "Antiques & Collectibles",
            "Children's Short Story Collections",
            "Antiques & Collectibles Encyclopedias",
            "Romance Anthologies",
            "Romance Collections & Anthologies",
            "Christian Short Stories",
            "Inspirational Romance",
            "Western & Frontier Christian Romance",
            "Lifestyle",
            "Dog Hip & Joint Care",
            "Cat Litter",
            "Dog ID Tags",
            "Dog Muzzles",
            "Dog Squeak Toys",
            "Dog Training Leashes",
            "Dog Bed Mats",
            "Standard Dog Leashes",
            "Dog Rawhide Sticks",
            "Dog Waste Bags",
            "Rubber Bands",
            "Hair Styling Products",
            "Hummingbird Food",
            "Do-It-Yourself Home Improvement",
            "Home Repair",
            "How-to & Home Improvements",
            "Crafts, Hobbies & Home",
            "Carpentry",
            "Home Heating & Air Conditioning",
            "Masonry Home Improvement",
            "Roofing Home Remodeling",
            "Mechanical Engineering",
            "Engineering Reference",
            "Home Maintenance & Repair",
            "Home Carpentry",
            "Reference How-to & Home Improvement",
            "Success Self-Help",
            "History & Theory of Politics",
            "Dystopian Fiction",
            "Business Leadership",
            "Self-Help",
            "Coming of Age Fiction",
            "Post-Apocalyptic Science Fiction",
            "Action & Adventure Fiction",
            "Dystopian Science Fiction",
            "Political History",
            "Fantasy Adventure Fiction",
            "Women's Adventure Fiction",
            "Action & Adventure Literary Fiction",
            "Business Management & Leadership",
            "Table Lamps",
            "Lamp Sets",
            "Desk Lamps",
            "Lamps, Bases & Shades",
            "Lamp Shades",
            "Picture Lights & Mini Accent Spotlights",
            "Novelty Lighting",
            "Patio Wall Light Fixture",
            "Kids' Room Decor Lamps & Lighting",
            "Home Décor Accents",
            "Projection Lamps",
            "Kitchen Cookware",
            "Skillets",
            "Cookware & Baking Pans",
            "Specialty Cookware",
            "Steamers, Stock & Pasta Pots",
            "Omelet Pans",
            "Air Fryers",
            "Hardware",
            "Cabinet & Furniture Pulls",
            "Garage Door Hardware",
            "Door Hardware & Locks",
            "Garage Door Springs & Wires",
            "Pocket & Bi-Fold Door Hardware",
            "Screen Door Hardware",
            "Furniture Hardware",
            "Cabinet Hardware",
            "Hardware Adhesives & Sealers",
            "Nut & Bolt Assortment Sets",
            "Industrial Hardware",
            "Screw & Bolt Assortment Sets",
            "Stem Casters",
            "Casters",
            "Hardware Brackets",
            "Commercial Door Hardware",
            "Office Furniture Accessories",
            "Home Automation Hubs & Controllers",
            "Home Automation Modules",
            "LED Bulbs",
            "Home Automation Devices",
            "Electrical Light Switches",
            "Electrical Outlet Switches",
            "One-Piece Toilets",
            "Home Programmable Thermostats",
            "Electric Plugs",
            "Electrical Switches",
            "Home Security Systems",
            "Remote Controls",
            "Remote-Control Extenders",
            "Audio & Video Speaker Accessories",
            "Security Sensors & Alarms",
            "Surveillance Video Equipment",
            "Smart Home",
            "Surveillance & Security Cameras",
            "Complete Surveillance Systems",
            "Key Racks",
            "Refillable Cosmetic Containers",
            "Outdoor Doormats",
            "Dog Beds",
            "Dog Soft-Sided Carriers",
            "Cat Beds",
            "Basic Cat Bowls",
            "Cat Soft-Sided Carriers",
            "Place Mats",
            "Tablecloths",
            "Aprons",
            "Shower Curtain Sets",
            "Robotic Vacuums",
            "Tapestries",
            "Bath Rugs",
            "Mouse Pads",
            "Men's Hats & Caps",
            "Medical",
            "Health & Fitness",
            "Indoor Safety Gates",
            "Pickle-Ball Equipment",
            "Dog Supplies",
            "Dog Travel Bowls",
            "Dog Shedding Tools",
            "Dog Doorbells",
            "Dog Bed Blankets",
            "Dog Hair Removal Products",
            "Dog Training Pads & Trays",
            "Travel Cat Bowls",
            "Dry Dog Food",
            "Canned Dog Food",
            "Dog Food",
            "Dehydrated Dog Food",
            "Dog Food Toppings, Gravies & Sauces",
            "Dog Food Pouches",
            "Cat Litter Boxes",
            "Cat Activity Trees",
            "Standard Cat Litter Boxes",
            "Cat Mice & Animals Toys",
            "Cat Scratching Posts",
            "Dog Bowls",
            "Canned Cat Food",
            "Cat Shampoos",
            "Cat Litter Waste Receptacles",
            "Dry Cat Food",
            "Wet Cat Food",
            "Cat Food",
            "Cat Food Pouches",
            "Aquarium Décor Ornaments",
            "Aquarium Filters",
            "Aquariums",
            "Fish Bowls",
            "Fish Breeding Tanks",
            "Aquarium Starter Kits",
            "Human Resources & Personnel Management",
            "Motivational Management & Leadership",
            "Customer Relations",
            "Business Motivation & Self-Improvement",
            "New Age & Spirituality",
            "Fishing Equipment",
            "Men's Shoes",
            "Men's Sandals",
            "Men's Athletic & Outdoor Sandals & Slides",
            "Women's Shoes",
            "Women's Slippers",
            "Business & Investing",
            "Motivational Business Management",
            "Business Teams",
            "Cod",
            "Salmon",
            "Frozen Seafood Burgers & Patties",
            "Frozen Fish",
            "Kids' Plush Toy Pillows",
            "Bird Watching",
            "Children's Bird Books",
            "Bird Field Guides",
            "Ornithology",
            "Nature & Ecology",
            "Environmentalist & Naturalist Biographies",
            "Biographies",
            "Traveler & Explorer Biographies",
            "Behavioral Sciences",
            "Women's Fashion Scarves",
            "Women's Wallets",
            "Romance",
            "VHS",
            "Birdhouses",
            "Outdoor Décor",
            "Skin Care Products",
            "Facial Cleansing Washes",
            "Facial Serums",
            "Facial Skin Care Products",
            "Face Moisturizers",
            "Facial Masks",
            "Facial Cleansing Products",
            "Facial Toners & Astringents",
            "Facial Cleansing Gels",
            "Facial Treatments & Masks",
            "Hair Color",
            "Salon & Spa Chairs",
            "Role Playing Games",
            "Simulation Games",
            "Games for Kids",
            "Arcade Games",
            "Scissor Racks",
            "Bedside Shampoo Basins & Trays",
            "Daily Living Hair Dryer Aids",
            "Health Care Products",
            "Household Supplies",
            "Latex Gloves",
            "Shoe Insoles",
            "Engine & Parts Fluid Cleaners",
            "Hand Cleaners",
            "Garage & Shop Products",
            "Janitorial & Sanitation Supplies",
            "Commercial Soap & Lotion Dispensers",
            "Professional Dental Supplies",
            "Professional Medical Supplies",
            "Science Lab Wipes",
            "Home Cleaning, Caretaking & Relocating",
            "Green Housecleaning",
            "Health, Fitness & Dieting",
            "Grooming & Style",
            "Sustainable Living",
            "Home Improvement & Design Books",
            "Medical Books",
            "Cosmetics",
            "Cleaning, Caretaking & Relocating How-to",
            "Beauty, Grooming, & Style",
            "Healthy Living",
            "Infectious Disease",
            "Skin Ailments",
            "Hair Beauty & Fashion",
            "Physical Impairments",
            "Holistic Medicine",
            "Hair Shampoo",
            "Facial Creams & Moisturizers",
            "Multivitamins",
            "Vitamin D Supplements",
            "Blended Vitamin & Mineral Supplements",
            "Omega 3 Nutritional Supplements",
            "Vitamin B12 Supplements",
            "Vitamin B-Complex Supplements",
            "Hair, Skin & Nails Vitamin Supplements",
            "Vitamin E Supplements",
            "Children's Vitamins",
            "Vitamins & Dietary Supplements",
            "Alternative Health & Vitamins",
            "Nutrition of Vitamins & Supplements",
            "Vitamins & Supplements",
            "Alternative Medicine",
            "Nutrition",
            "Dog Probiotic Supplements",
            "E-commerce Professional",
            "Web Marketing",
            "Direct Marketing",
            "Marketing",
            "Bath & Shower Sets",
            "Women's Eau de Parfum",
            "Women's Razor Systems",
            "Women's Replacement Razor Blade Cartridges & Refills",
            "Women's Disposable Shaving Razors",
            "Men's Shaving & Grooming Sets",
            "Facial Sunscreens",
            "Cat Litter Box Liners",
            "L-Arginine Nutritional Supplements",
            "Assorted Snack Cookies",
            "Breads & Bakery",
            "Snack Food Gifts",
            "Single-Serve Coffee Capsules & Pods",
            "Canned & Jarred Fish",
            "Ammunition & Magazine Pouches & Holders",
            "Lab Microcentrifuge Tube Racks",
            "Medical Specimen Collection Containers",
            "Commercial Odor & Drain Maintainers",
            "Household Stains",
            "Flooring Materials",
            "Bathroom Accessories",
            "Box Mailers",
            "Women's Boots",
            "Toilet Paper",
            "Dish Soap",
            "Feminine Care",
            "Bulk Quantity Toilet Tissue",
            "Bulk Quantity Hand Soaps",
            "Food Service Equipment & Supplies",
            "Bulk Quantity Feminine Hygiene Products",
            "Hand Wash",
            "Foot & Hand Care",
            "Bathroom Countertop Soap Dispensers",
            "Household Cleaning Supplies",
            "Camera Batteries",
            "Personal Health",
            "Health Care Delivery",
            "Health Insurance",
            "Health Policy",
            "Economic Policy & Development",
            "Diets",
            "Weight Loss Diets",
            "21st Century American History",
            "Sociological Study of Medicine",
            "United States History",
            "Medical Law & Legislation",
            "United States National Government",
            "Other Diet Books",
            "Sports Training",
            "Exercise & Fitness",
            "Sports Medicine",
            "Diets & Weight Loss",
            "Triathlons",
            "Science & Math",
            "Medical Nutrition",
            "Sports Nutrition Endurance & Energy Chews & Gels",
            "Sports Nutrition Products",
            "Weight Training",
            "Nursing Nutrition",
            "Baby Bottle Accessories",
            "Baby Bottles",
            "Baby Bathing Tubs & Seats",
            "Nursery Blankets",
            "Baby Safety Products",
            "Baby Monitors",
            "Diaper Wipes & Refills",
            "Toddler Dishes",
            "Baby Bibs",
            "Baby Teether Toys",
            "Baby Girls' Clothing & Shoes",
            "Baby Boy's Clothing",
            "Baby Girls' Hats & Caps",
            "Baby Boys' Clothing Sets",
            "Baby Girls' Clothing Sets",
            "Baby Boys' One-Piece Rompers",
            "Baby Boys' Clothing & Shoes",
            "Baby Girls' Layette Sets",
            "Baby Boys' Accessories",
            "Baby Girls' Shoes",
            "Baby Girls' Novelty Clothing",
            "Baby Boys' Novelty Clothing",
            "Baby Boys' Novelty One-Piece Rompers",
            "Baby Rattles",
            "Baby Musical Toys",
            "Ride-On Toys",
            "Children's Word Books",
            "Children's Vocabulary & Spelling Books",
            "Children's Foreign Language Books",
            "Braces, Splints & Supports",
            "Baby & Child Care Products",
            "Laundry Stain Removers",
            "Bandages & Bandaging Supplies",
            "Medical Supplies & Equipment",
            "Mobility Aids & Equipment",
            "First Aid Kits",
            "First Aid Supplies",
            "Athletic & Aviation Pulse Oximeters",
            "Canes, Crutches & Accessories",
            "Bathroom Safety, Aids & Accessories",
            "Walking Canes",
            "First Aid Gauze",
            "Medical Furniture & Patient Transport",
            "Stethoscopes",
            "Medical Overbed Tables",
            "Medical Pen Lights",
            "Medical Scissors & Shears",
            "Medical Casting Supplies",
            "Otoscopes",
            "Medical Gauze",
            "Lab Dissection Kits",
            "Tool Bags",
            "Camping First Aid Kits",
            "Laboratory Notebooks",
            "Uniforms, Work & Safety Clothing",
            "Baby & Toddler Toys",
            "Kids Basic Skills Development Toys",
            "Grown-Up Toys",
            "Toy Soccer Products",
            "Miniature Novelty Toys",
            "Kids' Scratchboard Art Kits",
            "Dolls & Accessories",
            "Anime",
            "Alternative Rock",
            "Folk",
            "Children's Music",
            "Disney Music",
            "Children's Arts, Music & Photography Books",
            "Children's Science & Nature Books",
            "Children's Physics Books",
            "Children's Activity Books",
            "Children's Game Books",
            "Children's Model Building Books",
            "Plug & Play Video Games",
            "Dark Horse Comics & Graphic Novels",
            "Media Tie-In Graphic Novels",
            "Teen & Young Adult TV, Movie, Video Game Adaptations",
            "Pop Culture in Graphic Design",
            "Pop Culture",
            "Kids' & Baby Wall Stickers",
            "Night-Lights",
            "Toy RC Vehicles",
            "Light-Up Toys",
            "Seasonal Lighting",
            "Nursery Night Lights",
            "Kids' Backpacks",
            "Boys' Novelty Clothing",
            "Girls' Novelty Tops & Tees",
            "Women's Novelty Clothing",
            "Men's Novelty Clothing",
            "Cupcake Toppers",
            "Kids",
            "Baby Boys' Bodysuits",
            "Women's Bridal Rings Sets",
            "Women's Bracelets",
            "Women's Earrings",
            "Women's Promise Rings",
            "Girls' Earrings",
            "Girls' Bracelets",
            "Girls' Necklaces",
            "Men's Jewelry",
            "Men's Earrings",
            "Men's Necklaces",
            "Boys' Bracelets",
            "Boys' Necklaces",
            "Area Rugs",
            "Foreign Films",
            "Home Design & Construction",
            "Suspense Thrillers",
            "Murder Thrillers",
            "Thrillers & Suspense",
            "Kidnapping Thrillers",
            "Children's Explore the World Books",
            "Electronica",
            "Soundtracks",
            "Home Design",
            "Thrillers",
            "Suspense",
            "Crime Fiction",
            "Murder",
            "Women's Lingerie",
            "Women's Dresses",
            "Plus-Size Lingerie",
            "Petite-Size Baby Doll Lingerie",
            "Women's Robes",
            "Women's Plus Sleepwear",
            "Women's Petite Robes",
            "Petite-Size Lingerie",
            "Bridal Veils",
            "Kids' Party Supplies",
            "Party Favors",
            "Artificial Flowers",
            "Home Décor Products",
            "Event & Party Supplies",
            "Wall & Tabletop Picture Frames",
            "Decorative Signs",
            "Party Photobooth Props",
            "Wooden Games",
            "Weddings",
            "Marriage",
            "Gift Decorating",
            "Wedding Planners",
            "Wedding Showers, Parties & Receptions",
            "Calendars",
            "Women's Exotic Bustiers & Corsets",
            "Women's Novelty Tops & Tees",
            "Cards & Card Stock",
            "Chalkboards",
            "Decorating Tools",
            "Glassware & Drinkware",
            "Table Place Cards & Place Card Holders",
            "Scrapbooking Stickers & Sticker Machines",
            "Digital Video",
            "Paper & Plastic Household Supplies",
            "Wedding",
            "Garden Arbors",
            "Girls' Underwear",
            "Girls' Skirts & Skorts",
            "Girls' Clothing",
            "Girls' Tops & Tees",
            "Girls' Outerwear Jackets & Coats",
            "Girls' Sleepwear",
            "Girls' Socks & Tights",
            "Girls' Swimwear",
            "Girls' Fashion Hoodies & Sweatshirts",
            "Women's Clothing",
            "Women's Tops, Tees & Blouses",
            "Women's Fashion Hoodies & Sweatshirts",
            "Women's Sweaters",
            "Women's Plus Sweaters",
            "Women's Petite Pullover Sweaters",
            "Women's Plus Tops & Tees",
            "Boys' Clothing",
            "Boys' Button-Down & Dress Shirts",
            "Boys' Outerwear Jackets & Coats",
            "Boys' Swimwear",
            "Boys' Sleepwear",
            "Boys' Suits & Sport Coats",
            "Boys' Fashion Hoodies & Sweatshirts",
            "Men's Outerwear Jackets & Coats",
            "Women's Shoulder Handbags",
            "Women's Top-Handle Handbags",
            "Women's Tote Handbags",
            "Women's Crossbody Handbags",
            "Women's Satchel Handbags",
            "Women's Handbags, Purses & Wallets",
            "Women's Hobo Handbags",
            "Women's Clutch Handbags",
            "Women's Clutches & Evening Handbags",
            "Diaper Bags",
            "Travel Tote Bags",
            "Messenger Bags",
            "Foundation Makeup",
            "Body Scrubs",
            "Fashion Headbands",
            "Makeup Brush Sets & Kits",
            "Teen & Young Adult Girls & Women Fiction",
            "Teen & Young Adult Fairy Tale & Folklore Adaptations",
            "Teen & Young Adult Fairy Tales & Folklore",
            "Teen & Young Adult Science Fiction & Fantasy",
            "Teen & Young Adult Books",
            "Teen & Young Adult Classic Literature",
            "Beauty",
            "Contemporary Romance",
            "Military Romance",
            "Teen & Young Adult Literature & Fiction eBooks",
            "Teen & Young Adult Fantasy eBooks",
            "Teen & Young Adult Myth & Legend eBooks",
            "Teen & Young Adult Girls & Women Fiction eBooks",
            "Teen & Young Adult Fairy Tales & Folklore Adaptations eBooks",
            "Teen & Young Adult Fairy Tales & Folklore eBooks",
            "Stationery",
            "Blank Note Cards",
            "Notebooks & Writing Pads",
            "Greeting Card Mailing Envelopes",
            "Business Mailing Envelopes",
            "Self-Stick Note Pads",
            "Paper Stationery",
            "Blank Note Card Sets",
            "Decorative Craft Paper",
            "Scrapbooking & Stamping Supplies",
            "Parchment Paper",
            "Baby Gift Sets",
            "Kids' Stickers",
            "Wall Sconces",
            "LED Strip Lights",
            "Posters & Prints",
            "Corner Shelves",
            "Throw Pillow Covers",
            "Artificial Trees",
            "Decorative Plaques",
            "Storage Benches",
            "Hanging Planters",
            "Wall-Mounted Wine Racks",
            "Salt & Pepper Shaker Sets",
            "Home Decorating",
            "Parts & Accessories",
            "Media Organizers",
            "Aromatherapy Products",
            "Aromatherapy Diffusers",
            "Jewelry Towers",
            "Nursery Wall Décor",
            "Dog Food Storage",
            "Handmade Prints",
            "Wall Art",
            "Paintings",
            "Wall Sculptures",
            "Job Hunting",
            "Individual Artist Essays",
            "Business of Art Reference",
            "Individual Artists",
            "Art Instruction & Reference",
            "Art Reference",
            "Cake Pop & Mini Cake Makers",
            "Cheerleading Apparel",
            "Baseball & Softball Clothing",
            "Girls' Cheerleading Apparel",
            "Girls' Football Clothing",
            "Basketball Clothing",
            "Football Clothing",
            "Baseball & Softball Equipment",
            "Hunting Clothing",
            "Women's Basketball Clothing",
            "Kids' Football Gear",
            "Men's Big & Tall Athletic Supporters",
            "Men's Activewear",
            "Cycling Clothing",
            "Women's Climbing Clothing",
            "Athletic Tapes & Wraps",
            "First Aid Tape",
            "Women's Activewear",
            "Hunting Equipment",
            "Hunting Camouflage Accessories",
            "Hunting Apparel",
            "Archery Bows",
            "Hunting & Shooting Gun Stock Accessories",
            "Fixed Blade Hunting Knives",
            "Tactical Paracord",
            "Hunting Seats",
            "Camping Foot Warmers",
            "Camping Survival Kits",
            "Camping Headlamps",
            "Men's Novelty Hoodies",
            "Men's Novelty Shirts",
            "Men's Novelty Jackets & Coats",
            "Hunting",
            "Hunting & Fishing Humor",
            "African-American & Black Biographies",
            "Sports Biographies",
            "Game Cooking",
            "Cooking for One or Two",
            "Biology of Wildlife",
            "Fishing",
            "Shooting in Hunting",
            "Sports Hunting",
            "Handheld Flashlights",
            "Thermoses",
            "Novelty Coffee Mugs",
            "Board Games",
            "Team Sports",
            "Sports Fan Outdoor Flags",
            "Sports Fan Kitchen & Dining Products",
            "Sports Fan Ornaments",
            "Sports Fan Prints & Posters",
            "Sports Fan Home Décor",
            "Sports Fan Key Chains",
            "Sports Fan Alarm Clocks",
            "Sports Fan Toys & Game Room",
            "Sports Fan Pens",
            "Sports Fan Entry Mats",
            "Outdoor Flags & Banners",
            "Desk & Shelf Clocks",
            "Bottle Openers",
            "Tabletop Wine Racks",
            "Wine Stoppers",
            "Sports & Outdoors",
            "Sociology",
            "General Library & Information Sciences",
            "Communication Reference",
            "Television",
            "Politics & Government",
            "Academic & Commercial Writing Reference",
            "Business of Art",
            "Political Science",
            "Specific Politics & Government Topics",
            "Golf Club Bag Accessories",
            "Golf Equipment",
            "Golf Iron Sets",
            "Men's Golf Clothing",
            "Women's Golf Clothing",
            "Golf Swing Trainers",
            "Golf Gloves",
            "Golf Divot Tools",
            "Golf Tees",
            "Golf Towels",
            "Men's Clothing",
            "Men's Golf Shoes",
            "Men's Shirts",
            "Men's Shorts",
            "Men's Pants",
            "Men's Belts",
            "Golf",
            "Sports Coaching",
            "Golf Biographies",
            "Sports Encyclopedias",
            "Sports Reference",
            "Memoirs",
            "Sports Fan Golf Bag Towels",
            "Sports Fan Golf Equipment",
            "Men's Novelty Socks",
            "Kids' Sports",
            "Golf Games",
            "Leisure Sports & Games Equipment",
            "Darts",
            "Hospitality, Travel & Tourism",
            "Human Geography",
            "Sports History",
            "Public Affairs & Policy Politics Books",
            "Park & Recreation Industry",
            "Cultural Anthropology",
            "Sociology of Sports",
            "Popular Culture",
            "Pool Rafts & Inflatable Ride-ons",
            "Blues",
            "Sports Romance",
            "Fantasy Romance",
            "Short Story Literary Criticism",
            "Parenting & Relationships",
            "Holiday Romance",
            "Paranormal Romance",
            "Romance Manga",
            "Fantasy & Futuristic Romance",
            "Erotica",
            "Science Fiction Romance",
            "Foreign Language Instruction",
            "Sports Accessories",
            "Craft & Hobby Fabric",
            "Martial Arts Protective Foot Gear",
            "Toddler Cups",
            "Camp Kitchen Equipment",
            "Camping Tents",
            "Camping & Hiking Equipment",
            "Camping Lanterns",
            "Family Camping Tents",
            "Camping Hammocks",
            "Camping Pillows",
            "Camping Sleeping Bag Compression Sacks",
            "Self-Inflating Camping Pads",
            "Travel Pillows",
            "Toiletry Bags",
            "Children's Ape & Monkey Books",
            "Camping",
            "Children's Sports & Outdoors Books",
            "Barbecuing & Grilling",
            "Camping & RV Cooking",
            "Outdoor Cooking",
            "Tactical Backpacks",
            "Automotive Garbage Cans",
            "Toaster Ovens",
            "Card Games",
            "Outdoor Canopies",
            "Multitools",
            "Headlamps",
            "Female Urinals",
            "Women's Cycling Clothing",
            "Men's Cycling Clothing",
            "Cycling Equipment",
            "Cycling Accessories",
            "Boys' Cycling Clothing",
            "Bike Handlebar Bags",
            "Men's Cycling Shorts",
            "Bike Taillights",
            "Bike Multifunction Tools",
            "Men's Sunglasses",
            "Men's Cycling Shoes",
            "Cycling",
            "Adventure Travel",
            "Cycling Travel Guides",
            "Travelogues & Travel Essays",
            "Sports Humor",
            "French History",
            "European History",
            "Italian History",
            "Sunglasses",
            "Water Bottles",
            "Sports & Outdoor Biographies",
            "Special Interests",
            "Educational",
            "Women's Sunglasses",
            "Skateboarding Knee Pads",
            "Kids' Cycling Protective Gear",
            "Inline & Roller Skating Knee Pads",
            "Kids' Bike Helmets",
            "Inline & Roller Skating Protective Gear",
            "Skateboarding Equipment",
            "Cycling Protective Gear",
            "Adult Bike Helmets",
            "Inline & Roller Skating Equipment",
            "BMX Protective Gear",
            "Powersports Chest Protectors",
            "Deep Groove Ball Bearings",
            "Mechanical Pulleys",
            "Protective Body Equipment",
            "Water Sport Towables",
            "Water Sports",
            "Children's Water Sports Books",
            "Water Sports Magazines",
            "Boating Equipment",
            "Climbing Equipment",
            "Climbing Slings & Runners",
            "Climbing Holds",
            "Climbing Chalk",
            "Climbing Belay & Rappel Equipment",
            "Climbing Gloves",
            "Climbing Harnesses",
            "Locking Climbing Carabiners",
            "Climbing Rope, Cord & Webbing",
            "Climbing Helmets",
            "Men's Climbing Shoes",
            "Men's Socks",
            "Mountaineering",
            "Mountain Climbing",
            "Rock Climbing",
            "Extreme Sports",
            "Composer & Musician Biographies",
            "Strength Training Hand Strengtheners",
            "Biographies & Memoirs",
            "Adventurer & Explorer Biographies",
            "Travel Biographies & Memoirs",
            "Travel Mugs & Tumblers",
            "Men's Interests Magazines",
            "Hiking & Camping Magazines",
            "Eczema, Psoriasis & Rosacea Care",
            "Body Lotions",
            "Automotive Replacement Engine Parts",
            "Emblems",
            "Electrical System Tools",
            "Automotive Replacement Brake Rotors",
            "Automotive Tail Light Assemblies",
            "Exterior Automotive Mirrors",
            "Parts Washers",
            "Automotive Replacement Long Engine Blocks",
            "Automotive Replacement Engine Blocks",
            "Power Tool Lubricants",
            "Car In-Dash Navigation GPS Units",
            "Lab Instruments & Equipment",
            "Lab Ultrasonic Cleaners",
            "Cyanoacrylate Adhesives",
            "Commercial All-Purpose Cleaners",
            "Carbon Fiber Sheets",
            "All-Purpose Household Cleaners",
            "Household Mop Buckets",
            "Civil Service Test Guides",
            "Engine Tools",
            "Tool Sets",
            "Automotive Tools & Equipment",
            "Body Repair Upholstery & Trim Tools",
            "Automotive Clips",
            "Brake Repair Brake Adjusting Tools",
            "Brake Repair Brake Spreading Tools",
            "Fuel Line Disconnect Tools",
            "Engine Timing Belt Tools",
            "Code Readers & Scan Tools",
            "Socket Screwdriver Bits",
            "Nut Drivers",
            "Power Sander Accessories",
            "Wrenches",
            "Tool Belts",
            "Magnetic Sweepers",
            "Socket Wrenches",
            "Protective Arm Sleeves",
            "Metalworking Chisels",
            "Play Sets & Playground Equipment",
            "Vehicle Electronics",
            "Radio Antennas",
            "Boomboxes",
            "Power Converters",
            "GPS Trackers",
            "Boating",
            "Video Surveillance Equipment",
            "Camcorders",
            "Office Electronics Products",
            "Outdoor Power & Lawn Equipment",
            "Automotive Tops & Roofs",
            "Hunting & Shooting Accessories",
            "Passenger Car All-Season Tires",
            "Tires",
            "Light Truck & SUV All-Terrain & Mud-Terrain Tires",
            "Tire Repair Tools",
            "Passenger Car Touring Tires",
            "Passenger Car Performance Tires",
            "Light Truck & SUV All-Season Tires",
            "Analog Tire Pressure Gauges",
            "Tire Repair Kits",
            "Tire Covers",
            "Auto Tire & Wheel Services",
            "Sports Fan Tire Covers",
            "Motherhood",
            "Happiness Self-Help",
            "RC Vehicle Wheels & Tire Sets",
            "RC Vehicle Tires",
            "Automotive Replacement Cigarette Lighter & Parts",
            "Motorcycles & ATVs",
            "Motorcycle Protective Coats & Vests",
            "Powersports Accessories",
            "Powersports Handlebar Accessories",
            "Motorcycle & Powersports Helmets",
            "Powersports Tool Sets",
            "Zen Philosophy",
            "Religion & Spirituality",
            "Emotional Mental Health",
            "Medical General Psychology",
            "Philosophy",
            "Psychology & Counseling",
            "Eastern Philosophy",
            "Travel Writing Reference",
            "Bike Tool Kits",
            "Motorcycles",
            "Pocket Knives & Folding Knives",
            "Kids' Electric Vehicles",
            "Pizza Cutters",
            "Clocks",
            "RV Cleaning, Storage & Maintenance",
            "RV Awnings, Screens & Accessories",
            "RV Parts & Accessories",
            "RV Furnishings & Interior Accessories",
            "RV Waste Water & Sanitation Products",
            "Automotive Light Bulbs",
            "RV Interior Accessories",
            "Automotive Doors",
            "RV Ventilation",
            "RV Water Heaters, Pumps & Accessories",
            "Faucet Flanges",
            "Faucet Parts",
            "Cabinet & Furniture Door Catches",
            "Garden Hose Parts & Connectors",
            "Grilling & BBQ Utensils",
            "Cognitive Psychology",
            "Military History",
            "Medical Cognitive Psychology",
            "Children's Transportation Books",
            "Children's Cars & Trucks Books",
            "History of Military Vehicles",
            "Conventional Weapons & Warfare History",
            "Armored Vehicles Weapons & Warfare History",
            "Engineering",
            "Model Building",
            "Play Vehicles",
            "Grown-Up Die-Cast & Toy Vehicles",
            "Children's Die-Cast Vehicles",
            "Toy Vehicle Playsets",
            "Action Figure Vehicles",
            "Pull Back Vehicles",
            "Pre-Built Model Ground Vehicles",
            "Toy Remote Control & Play Vehicles",
            "Drying Pads",
            "Parking Gadgets",
            "Yard Signs",
            "Rubber Flooring",
            "Extension Cords",
            "Utility Knives",
            "Garage Cabinets & Storage Systems",
            "Garage Door Opener System Parts",
            "Sports Equipment & Supplies",
            "Automotive Engineering",
            "Lab Spill Response Kits",
            "Reference eBooks",
            "Cord Reels",
            "Indoor Snowboard Storage",
            "Toilet Plungers & Holders",
            "Commercial Toilet Plungers & Holders",
            "Quick Connect Hose Fittings",
            "Wire Rope Thimbles",
            "Electronic Components",
            "Rope",
            "Boat Deck Hardware",
            "Water Supply & Land Use",
            "Water Quality & Treatment",
            "Industries",
            "Business Ethics",
            "Business Purchasing & Buying",
            "Fixed Showerheads",
            "Lab Refrigerators",
            "Stove Safety Covers & Appliance Latches",
            "Industrial Health & Safety",
            "Technology Safety & Health",
            "Safety & First Aid",
            "Aviation",
            "Safety & Health Engineering",
            "Safety & Health in Technology",
            "Personal Protective Equipment & Safety Gear",
            "Restaurant & Food Industry",
            "Business Management",
            "Service Industry",
            "Leadership Training",
            "Systems & Planning",
            "Production & Operations",
            "Woks & Stir-Fry Pans",
            "Food Steamers",
            "Steamer Cookware",
            "Rice Cookers",
            "Food Strainers",
            "Business Leadership Training",
            "Business Education & Reference",
            "Cooktop Parts & Accessories",
            "Men's Health Care & Food Service Shoes",
            "Women's Health Care & Food Service Shoes",
            "Material Handling",
            "Hoists",
            "Manual Lever Hoists",
            "Round Slings",
            "Slip Hooks",
            "Material Handling Products",
            "Swivels",
            "Manual Hoists",
            "Grab Hooks",
            "Lifting Clamps",
            "Hand Chain Hoists",
            "Hoist Rings",
            "Industrial Manufacturing Systems",
            "Business Operations Research",
            "Industrial Manufacturing",
            "Technology",
            "Manufacturing Engineering",
            "Purchasing & Buying Industry",
            "Business Production & Operations",
            "Entrepreneurship Management",
            "Industrial Engineering",
            "Women's Leather & Faux Leather Jackets & Coats",
            "Women's Pants",
            "Women's Novelty Sleep & Loungewear",
            "Women's Novelty Dresses",
            "Women's Skateboarding Clothing",
            "Women's Exercise & Fitness Apparel",
            "Boxing Clothing",
            "Men's Skullies & Beanies",
            "Men's Exercise & Fitness Apparel",
            "Traditional & Cultural South Asian Wear",
            "Traditional & Cultural Pan-African Wear",
            "Traditional & Cultural East Asian Wear",
            "Style & Clothing",
            "Historical Study",
            "Men's Grooming & Style",
            "Fashion History",
            "Theater",
            "Men's Gender Studies",
            "Men's Skiing Clothing",
            "Gender Studies",
            "History",
            "Baby Girls' One-Piece Footies",
            "Baby Girls' Clothing",
            "Ski Clothing",
            "Baby Boys' Novelty Clothing Sets",
            "Baby Boys' Novelty Tops",
            "Boys' Novelty Clothing Sets",
            "Doll Clothing & Shoes",
            "Baby Bibs & Burp Cloths Sets",
            "Baby Burp Cloths",
            "Boys' Activewear",
            "Boys' Football Clothing",
            "Boys' Baseball & Softball Clothing",
            "Boys' Soccer Clothing",
            "Ice Hockey Clothing",
            "Boys' Running Clothing",
            "Tennis Clothing",
            "Baby Girls' Dresses",
            "Sports Fan Clothing",
            "Baby Boys' Novelty Baby Bibs",
            "Baby Girls' Novelty Baby Bibs",
            "Baby Novelty Clothing",
            "Baby Boys' Novelty Bodysuits",
            "Baby Girls' Novelty Bodysuits",
            "Girls' Clothing Sets",
            "Doll Accessories",
            "Dolls",
            "Baby Boys' Costumes",
            "Baby Girls' Costumes",
            "Baby Bibs & Burp Cloths",
            "Baby Care Products",
            "Baby Bathing Products",
            "Girls' Sneakers",
            "Girls' Shoes",
            "Girls' Sandals",
            "Girls' Flats",
            "Girls' Boots",
            "Girls' Sport Sandals",
            "Girls' Dance Shoes",
            "Baby Girls' Sneakers",
            "Boys' Sneakers",
            "Girls' Running Shoes",
            "Girls' Athletic Shoes",
            "Girls' Walking Shoes",
            "Baby Boys' Sneakers",
            "Baby Boys' Shoes",
            "Boys' Shoes",
            "Running Footwear",
            "Baby Boys' Socks",
            "Girls' Uniform & School Shoes",
            "Girls' Oxfords",
            "Women's Costume Footwear",
            "Nursery Bedding",
            "Camera Flash Shoe Mounts",
            "Girls' Jewelry",
            "Women's Jewelry Sets",
            "Women's Anklets",
            "Women's Charm Bracelets",
            "Boys' Jewelry",
            "Jewelry Making Chains",
            "Jewelry Making Kits",
            "Handmade Piercing Jewelry",
            "Handmade Jewelry",
            "Jewelry Craft",
            "Feminist Theory",
            "Women's Studies",
            "Women in Art History & Criticism",
            "Jewelry Boxes & Organizers",
            "Men's Bracelets",
            "Men's Wrist Watches",
            "Men's Rings",
            "Men's Wedding Rings",
            "Women's Brooches & Pins",
            "Kids' Play Bracelets",
            "Kids' Fashion & Beauty Dress-Up Toys",
            "Kids' Jewelry Making Kits",
            "Sports Fan Jewelry & Watches",
            "Handmade Pendant Necklaces",
            "Handmade Charm Bracelets",
            "Handmade Necklace Chains",
            "Babies' Costumes",
            "Home Decor Gift Packages",
            "Hanging Jewelry Organizers",
            "Rhinestone & Sequin Embellishments",
            "Girls' Wrist Watches",
            "Girls' Watch Bands",
            "Novelty Watches",
            "Boys' Watches",
            "Boys' Wrist Watches",
            "Easy Listening",
            "Rock",
            "Toilet Training Products",
            "Baby Keepsake Frames",
            "Women's Watch Bands",
            "Women's Watches",
            "Men's Watch Bands",
            "Men's Watches",
            "Baby Girls' One-Piece Rompers",
            "Parenting",
            "Romantic Suspense",
            "General Constitutional Law",
            "Media & the Law",
            "Babysitting, Day Care & Child Care",
            "Handmade Boys' Clothing",
            "Handmade Girls' Clothing",
            "Contemporary Country",
            "Smartwatch Bands"


    );
    
    
}
